<?php $title = ' Afficher les Notes' ?>

<?php ob_start() ?>

<h1><?= htmlspecialchars($user->getFirstname()) .' '. htmlspecialchars($user->getLastname()) ?> </h1>

<ul>
    <?php foreach ($notes as $note) { ?>
    <li><?= htmlspecialchars($note->getSubject()) .' : '. htmlspecialchars($note->getResult())  ?></li>
    <?php } ?>
</ul>

<?php if(($appreciation)) { ?>   
    <fieldset>
        <legend>Commentaire</legend>
        <p><?= htmlspecialchars(ucfirst($appreciation->getComment())) ?></p>
        <h3><?= htmlspecialchars($appreciation->getMention()) ?></h3>
        <p><a href="?route=update&id=<?= $appreciation->getId() ?>">✏️</a> <a href="?route=delete&id=<?= $user->getId() ?>">❌</a></p>
        
    </fieldset>
<?php } else {?>
    <p><a href="?route=add&id=<?= $user->getId() ?>">Remplir le bulletin</a></p>
<?php } ?>

<p><a href="?route=index">Retour à la classe</a></p>

<?php $content = ob_get_clean() ?>

<?php 
require('base.phtml'); 
?>
