<?php $title = ' Modification Bulletin' ?>

<?php ob_start() ?>

<h1> Modifier le bulletin</h1>

<form action="?route=update" method="post">

    <label for="comment">Commentaire :</label><br>
    <textarea name="comment" cols="45" rows="6"  required><?= htmlspecialchars(ucfirst($appreciation->getComment())) ?></textarea>
    <div>
        <p>Mention :</p>
        <input type="radio" name="mention" value="Avertissement" <?= ($appreciation->getMention() === 'Avertissement') ? 'checked':'' ?>>
        <label for="mention">Avertissement</label>
        <input type="radio" name="mention" value="Encouragements" <?= ($appreciation->getMention() === 'Encouragements') ? 'checked':'' ?>>
        <label for="mention">Encouragements</label>
        <input type="radio" name="mention" value="Félicitations" <?= ($appreciation->getMention() === 'Félicitations') ? 'checked':'' ?>>
        <label for="mention">Félicitations</label>    
    </div>
    <input type="hidden" name="idUser" value="<?= $appreciation->getId_user() ?>">
    <p><input type="submit" value="Enregistrer"></p>
</form>


<p><a href="?route=show&id=<?= $appreciation->getId_user() ?>">Retour à l'élève</a></p>

<?php $content = ob_get_clean() ?>

<?php 
require('base.phtml'); 
?>
